[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_2 = "7DcNUJ6M2xqQEMwfaJ8VyLQJNw9nv3fospcPn1KRZLWv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
